#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Proc-InvokeEditor
Version  : 1.13
Release  : 15
URL      : https://cpan.metacpan.org/authors/id/M/MS/MSTEVENS/Proc-InvokeEditor-1.13.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/M/MS/MSTEVENS/Proc-InvokeEditor-1.13.tar.gz
Summary  : 'Interface to external editor from perl'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Proc-InvokeEditor-license = %{version}-%{release}
Requires: perl-Proc-InvokeEditor-perl = %{version}-%{release}
Requires: perl(Carp::Assert)
BuildRequires : buildreq-cpan
BuildRequires : perl(Carp::Assert)

%description
This archive contains the distribution Proc-InvokeEditor,
version 1.13:
Interface to external editor from perl

%package dev
Summary: dev components for the perl-Proc-InvokeEditor package.
Group: Development
Provides: perl-Proc-InvokeEditor-devel = %{version}-%{release}
Requires: perl-Proc-InvokeEditor = %{version}-%{release}

%description dev
dev components for the perl-Proc-InvokeEditor package.


%package license
Summary: license components for the perl-Proc-InvokeEditor package.
Group: Default

%description license
license components for the perl-Proc-InvokeEditor package.


%package perl
Summary: perl components for the perl-Proc-InvokeEditor package.
Group: Default
Requires: perl-Proc-InvokeEditor = %{version}-%{release}

%description perl
perl components for the perl-Proc-InvokeEditor package.


%prep
%setup -q -n Proc-InvokeEditor-1.13
cd %{_builddir}/Proc-InvokeEditor-1.13

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test || :

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Proc-InvokeEditor
cp %{_builddir}/Proc-InvokeEditor-1.13/LICENSE %{buildroot}/usr/share/package-licenses/perl-Proc-InvokeEditor/3090d0a6c20b10c1324c8c456ac2b6c3d69cebb1
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Proc::InvokeEditor.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Proc-InvokeEditor/3090d0a6c20b10c1324c8c456ac2b6c3d69cebb1

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
